version: '3.4'
services:
  selenium.test:
    #hostname: selenium.test
    image: selenium/standalone-chrome:3.14.0
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    environment:
      TZ: 'EST5EDT'
